/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ReviewItem = {
  _type: "reviewItem";
  name?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  source?: string;
  rating?: number;
  text?: string;
};

export type ServiceItem = {
  _type: "serviceItem";
  iconName?: string;
  title?: string;
  description?: string;
};

export type SeoMeta = {
  _type: "seoMeta";
  title?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Cta = {
  _type: "cta";
  label?: string;
  linkType?: string;
  internalPath?: "/" | "/produits" | "/a-propos" | "/contact";
  externalUrl?: string;
};

export type StoreHours = {
  _type: "storeHours";
  day?:
    | "monday"
    | "tuesday"
    | "wednesday"
    | "thursday"
    | "friday"
    | "saturday"
    | "sunday";
  isOpen?: boolean;
  open?: TimeValue;
  close?: TimeValue;
};

export type TimeValue = string;

export type WeeklyHours = {
  _type: "weeklyHours";
  monday?: DayHours;
  tuesday?: DayHours;
  wednesday?: DayHours;
  thursday?: DayHours;
  friday?: DayHours;
  saturday?: DayHours;
  sunday?: DayHours;
};

export type DayHours = {
  _type: "dayHours";
  isOpen?: boolean;
  open?: TimeValue;
  close?: TimeValue;
};

export type LegalNoticePage = {
  _id: string;
  _type: "legalNoticePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo?: SeoMeta;
};

export type PrivacyPage = {
  _id: string;
  _type: "privacyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo?: SeoMeta;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  surtitle?: string;
  title?: string;
  subtitle?: string;
  seo?: SeoMeta;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroSurtitle?: string;
  heroTitle?: string;
  heroSubtitle?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  storySurtitle?: string;
  storyTitle?: string;
  storyContent?: string;
  storyPhotos?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  storyCta?: Cta;
  seo?: SeoMeta;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type ProductsPage = {
  _id: string;
  _type: "productsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  surtitle?: string;
  title?: string;
  subtitle?: string;
  categorySections?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  seo?: SeoMeta;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  category?: CategoryReference;
  price?: number;
  tagline?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tagline?: string;
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroSurtitle?: string;
  heroTitle?: string;
  heroSubtitle?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroPrimaryCta?: Cta;
  heroSecondaryCta?: Cta;
  productsSurtitle?: string;
  productsTitle?: string;
  productsSubtitle?: string;
  featuredProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  aboutSurtitle?: string;
  aboutTitle?: string;
  aboutDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  aboutCta?: Cta;
  aboutPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  locationSurtitle?: string;
  locationTitle?: string;
  locationDescription?: string;
  locationPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  locationCta?: Cta;
  servicesItems?: Array<
    {
      _key: string;
    } & ServiceItem
  >;
  reviewsSurtitle?: string;
  reviewsTitle?: string;
  reviewsItems?: Array<
    {
      _key: string;
    } & ReviewItem
  >;
  galleryImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  bakeryName?: string;
  address?: string;
  phone?: string;
  email?: string;
  hours?: WeeklyHours;
  instagramUrl?: string;
  seo?: SeoMeta;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | ReviewItem
  | ServiceItem
  | SeoMeta
  | Cta
  | StoreHours
  | TimeValue
  | WeeklyHours
  | DayHours
  | LegalNoticePage
  | PrivacyPage
  | ContactPage
  | AboutPage
  | SanityImageCrop
  | SanityImageHotspot
  | CategoryReference
  | ProductsPage
  | Product
  | Slug
  | Category
  | ProductReference
  | HomePage
  | Settings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/queries/home-page.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage" && _id == "homePage"][0]{  heroSurtitle,  heroTitle,  heroSubtitle,  heroImage{ ..., alt },  heroPrimaryCta{ label, "href": select(linkType == "internal" => internalPath, externalUrl) },  heroSecondaryCta{ label, "href": select(linkType == "internal" => internalPath, externalUrl) },  productsSurtitle,  productsTitle,  productsSubtitle,  featuredProducts[]->{    _id,    name,    slug,    tagline,    price,    image{ ..., alt },    category  },  aboutSurtitle,  aboutTitle,  aboutDescription,  aboutCta{ label, "href": select(linkType == "internal" => internalPath, externalUrl) },  aboutPhoto{ ..., alt },  locationSurtitle,  locationTitle,  locationDescription,  locationPhoto{ ..., alt },  locationCta{ label, "href": select(linkType == "internal" => internalPath, externalUrl) },  servicesItems[]{    _key,    iconName,    title,    description  },  reviewsSurtitle,  reviewsTitle,  reviewsItems[]{    _key,    name,    source,    avatar,    rating,    text  },  galleryImages[]{ ..., alt }}
export type HOME_PAGE_QUERY_RESULT = {
  heroSurtitle: string | null;
  heroTitle: string | null;
  heroSubtitle: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  heroPrimaryCta: {
    label: string | null;
    href: string | null | "/" | "/a-propos" | "/contact" | "/produits";
  } | null;
  heroSecondaryCta: {
    label: string | null;
    href: string | null | "/" | "/a-propos" | "/contact" | "/produits";
  } | null;
  productsSurtitle: string | null;
  productsTitle: string | null;
  productsSubtitle: string | null;
  featuredProducts: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
    tagline: string | null;
    price: number | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | null;
      _type: "image";
    } | null;
    category: CategoryReference | null;
  }> | null;
  aboutSurtitle: string | null;
  aboutTitle: string | null;
  aboutDescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  aboutCta: {
    label: string | null;
    href: string | null | "/" | "/a-propos" | "/contact" | "/produits";
  } | null;
  aboutPhoto: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  locationSurtitle: string | null;
  locationTitle: string | null;
  locationDescription: string | null;
  locationPhoto: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  locationCta: {
    label: string | null;
    href: string | null | "/" | "/a-propos" | "/contact" | "/produits";
  } | null;
  servicesItems: Array<{
    _key: string;
    iconName: string | null;
    title: string | null;
    description: string | null;
  }> | null;
  reviewsSurtitle: string | null;
  reviewsTitle: string | null;
  reviewsItems: Array<{
    _key: string;
    name: string | null;
    source: string | null;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    rating: number | null;
    text: string | null;
  }> | null;
  galleryImages: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
    _key: string;
  }> | null;
} | null;

// Source: src/sanity/queries/products-page.ts
// Variable: PRODUCTS_PAGE_QUERY
// Query: *[_type == "productsPage" && _id == "productsPage"][0]{  surtitle,  title,  subtitle,  "categorySections": categorySections[]->{    _id,    name,    tagline,    "products": *[_type == "product" && category._ref == ^._id]{      _id,      name,      slug,      price,      tagline,      image{ ..., alt }    }  }}
export type PRODUCTS_PAGE_QUERY_RESULT = {
  surtitle: string | null;
  title: string | null;
  subtitle: string | null;
  categorySections: Array<{
    _id: string;
    name: string | null;
    tagline: string | null;
    products: Array<{
      _id: string;
      name: string | null;
      slug: Slug | null;
      price: number | null;
      tagline: string | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string | null;
        _type: "image";
      } | null;
    }>;
  }> | null;
} | null;

// Source: src/sanity/queries/settings.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "settings" && _id == "settings"][0]{  bakeryName,  instagramUrl,  address,  phone,  email,  hours {    monday { isOpen, open, close },    tuesday { isOpen, open, close },    wednesday { isOpen, open, close },    thursday { isOpen, open, close },    friday { isOpen, open, close },    saturday { isOpen, open, close },    sunday { isOpen, open, close }  },  seo {    title,    description  }}
export type SETTINGS_QUERY_RESULT = {
  bakeryName: string | null;
  instagramUrl: string | null;
  address: string | null;
  phone: string | null;
  email: string | null;
  hours: {
    monday: {
      isOpen: boolean | null;
      open: TimeValue | null;
      close: TimeValue | null;
    } | null;
    tuesday: {
      isOpen: boolean | null;
      open: TimeValue | null;
      close: TimeValue | null;
    } | null;
    wednesday: {
      isOpen: boolean | null;
      open: TimeValue | null;
      close: TimeValue | null;
    } | null;
    thursday: {
      isOpen: boolean | null;
      open: TimeValue | null;
      close: TimeValue | null;
    } | null;
    friday: {
      isOpen: boolean | null;
      open: TimeValue | null;
      close: TimeValue | null;
    } | null;
    saturday: {
      isOpen: boolean | null;
      open: TimeValue | null;
      close: TimeValue | null;
    } | null;
    sunday: {
      isOpen: boolean | null;
      open: TimeValue | null;
      close: TimeValue | null;
    } | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
  } | null;
} | null;
